// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {uidaemon} from '../models';
import {wailsui} from '../models';

export function Hide():Promise<void>;

export function HideWindow():Promise<void>;

export function OnConfigSaved():Promise<void>;

export function OnHidden():Promise<void>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function ShowResult(arg1:uidaemon.ResultPayload):Promise<void>;

export function ShowSettings():Promise<void>;

export function ShowTranslate():Promise<void>;

export function State():Promise<wailsui.UIState>;

export function Status():Promise<uidaemon.Status>;

export function Translate(arg1:string):Promise<wailsui.TranslateResult>;
