// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Hide() {
  return window['go']['wailsui']['App']['Hide']();
}

export function HideWindow() {
  return window['go']['wailsui']['App']['HideWindow']();
}

export function OnConfigSaved() {
  return window['go']['wailsui']['App']['OnConfigSaved']();
}

export function OnHidden() {
  return window['go']['wailsui']['App']['OnHidden']();
}

export function Quit() {
  return window['go']['wailsui']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['wailsui']['App']['SaveConfig'](arg1);
}

export function ShowResult(arg1) {
  return window['go']['wailsui']['App']['ShowResult'](arg1);
}

export function ShowSettings() {
  return window['go']['wailsui']['App']['ShowSettings']();
}

export function State() {
  return window['go']['wailsui']['App']['State']();
}

export function Status() {
  return window['go']['wailsui']['App']['Status']();
}

export function Translate(arg1) {
  return window['go']['wailsui']['App']['Translate'](arg1);
}
