// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveConfig(arg1) {
  return window['go']['wailsui']['App']['SaveConfig'](arg1);
}

export function State() {
  return window['go']['wailsui']['App']['State']();
}

export function Translate(arg1) {
  return window['go']['wailsui']['App']['Translate'](arg1);
}
