// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {wailsui} from '../models';

export function SaveConfig(arg1:config.Config):Promise<void>;

export function State():Promise<wailsui.UIState>;

export function Translate(arg1:string):Promise<wailsui.TranslateResult>;
